# azure pipeline for cypress

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd cypress-app
    npm install
  displayName: 'npm install cypress-app'
  
- script: |
    cd cypress-app
    npm run cy:cli    
  displayName: 'run cypress test for chrome'